version: "3"
services:

  mongodb:
    image: mongo
    ports:
    - 27017:27017
    network_mode: bridge

  mongo_express:
    image: mongo-express
    restart: always
    environment:
    - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
    - ME_CONFIG_MONGODB_SERVER=mongodb
    links:
    - mongodb:mongodb
    depends_on:
    - mongodb
    ports:
    - 8081:8081
    network_mode: bridge


  demo_app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: demo
    environment:
      - SPRING_ACTIVE_PROFILES=compose
    links:
    - mongodb:mongodb
    depends_on:
    - mongodb
    ports:
    - 8080:8080
    network_mode: bridge