global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
- job_name: 'payments-demo'
  metrics_path: '/prometheus'
  static_configs:
  - targets: ['demoapp:8080']
#    labels:
#      application: payments-demo